Списки и строки –одни из важных начальных понятий для любого дата сайентиста,поскольку на знании принципов работы с ними строится работа с препроцессингоми обработкой данных в python в целоми работы с модулем pandas в частности:


1.Дан произвольный список, содержащий только числа.Выведите результат сложения всех чисел больше 10

In [10]:
random_list = [5,6, 25, 13, 265, 2312,123, 5435, 345, 6,9, 231, 123, 123, 6645, 3453, 435, 3432]
print([num for num in random_list if num>10])
sum([num for num in random_list if num>10])

[25, 13, 265, 2312, 123, 5435, 345, 231, 123, 123, 6645, 3453, 435, 3432]


22960

2.Пусть задан список, содержащий строки.Выведите все строки, заканчивающиеся буквой r.

In [12]:
string_list = ['abra', 'cadabr', 'kreks', 'peks', 'feks', 'var', 'joint', 'her', 'why']
[string for string in string_list if string.endswith('r')]

['cadabr', 'var', 'her']

3.Сгенерируйте и выведите cлучайную строку размером 6 символов, содержащую только цифры. Строка должна содержать хотя бы одну цифру 3.

In [73]:
import random
#Через списки
list_of_ints = []
for i in range(6):
    list_of_ints.append(random.randint(0,9))
if ~(3 in list_of_ints):
    list_of_ints[random.randint(0,5)]=3
out_str = ''
for int_ in list_of_ints:
    out_str = out_str+str(int_)


    
#Более чистый вариант
out_str = ''
for i in range(6):
    out_str += str(random.randint(0,9))
if ~('3' in out_str):
    out_str = out_str.replace(out_str[random.randint(0,5)], '3')
out_str


'469536'

4.Пусть дана строка произвольной длины. Выведите информацию о том,сколько в ней символов и сколько слов.

In [89]:
random_string = 'sbdka sdnadn sdnadnond sdnadni dnasndoa djksadk dnsandjksa'
words = len(random_string.split(' '))
print (f'symbols: {len(random_string):1}  words: {words:1} ')

symbols: 58  words: 7 


Матрицы-следующее за списками и строками важное понятие.Широко используется в линейной алгебре.Находит свое применение в современных рекомендательных системах и архитектуре нейронных сетей:

1.Пусть дана матрица чисел размером NхN. Представьте данную матрицу ввиде списка. Выведите результат сложения всех элементов матрицы.

In [111]:
import numpy as np
N=5
matrix = np.random.randn(N,N)
list_ = matrix.tolist()
sum([sum(f) for f in list_])

-4.567536264367188

2.Пусть дана матрица чисел размером NхM. Найти столбец матрицы с максимальной суммой элементов.

In [129]:
import numpy as np
N=3
M=5
matrix1 = np.random.randn(N,M)
print(matrix1)
sums=([sum(row) for row in matrix1.transpose()])
print(sums)
print (sums.index(max(sums)))

[[-0.07232547  0.19717196  0.71846196 -1.66993121  2.40472192]
 [-0.77036856 -0.72095932 -2.09677669 -0.03781062 -0.22542008]
 [ 0.19555219  0.27083065 -0.44656541  0.05169683 -1.93894245]]
[-0.6471418484230893, -0.252956712451672, -1.824880150574956, -1.656044999576664, 0.2403593858267974]
4


Работа с динамичными структурами важная часть в имплементации вашего кода в продакшн-систему:

1.Пусть список студентов представлен в виде структуры [[No, ФИО, Возраст,Группа],[No, ФИО, Возраст, Группа],[No, ФИО, Возраст, Группа]]. Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}

In [137]:
students = [[1,'Ivanov Ivan Ivanovich',19,1054],[2,'Smirnov Petr Ivanovich',18,1025],[3,'Aleskeev Luka Fomich',23,5054]]
students_mod = [[s[0],[s[1],s[2],s[3]]] for s in students]
students_dict = dict(students_mod)

2.Добавьте к задаче №1 для словаря возможность (без преобразования словаря обратно в список) изменить группу студента. Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).

In [152]:
fio = 'Smirnov Petr Ivanovich'
new_group = 2054
for s in students_dict.items():
    if fio in s[1]:
        s[1][2] = new_group
students_dict

{1: ['Ivanov Ivan Ivanovich', 19, 1054],
 2: ['Smirnov Petr Ivanovich', 18, 2054],
 3: ['Aleskeev Luka Fomich', 23, 5054]}

3.Добавьте к задаче №1 для словаря возможность (без преобразования словаря обратно в список) изменить возраст студента.

In [153]:
fio = 'Smirnov Petr Ivanovich'
new_age = 21
for s in students_dict.items():
    if fio in s[1]:
        s[1][1] = new_age
students_dict

{1: ['Ivanov Ivan Ivanovich', 19, 1054],
 2: ['Smirnov Petr Ivanovich', 21, 2054],
 3: ['Aleskeev Luka Fomich', 23, 5054]}